version: 2.1

jobs:
  build-and-test:
  docker:
      # specify the version you desire here
      - image: circleci/node:jessie-browsers
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run webdriver-manager update
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
