version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:jessie-browsers
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run webdriver-manager update
      - run: npm run test
