version: 2.1
orbs:
  node: circleci/node:jessie-browsers
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run webdriver-manager update
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
