version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:jessie-browsers
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run webdriver-manager -- update --versions.chrome="70.0.3538.16"
      - run: google-chrome --version
      - run: npm run test
